# Lesson 1 Practice: NumPy Part 1
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L01-Numpy_Part1-Lesson.ipynb](./L01-Numpy_Part1-Lesson.ipynb).  



## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired.  

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [1]:
import numpy as np

## Task 2a: Creating Arrays

In the practice notebook, perform the following.  
- Create a 1-dimensional numpy array and print it.
- Create a 2-dimensional numpy array and print it.
- Create a 3-dimensional numpy array and print it.

In [2]:
OneD_array=np.array([1,2,3])
twoD_array=np.array([[1,2,3],[4,5,6]])
threeD_array=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(OneD_array)
print('\n')
print(twoD_array)
print('\n')
print(threeD_array)

[1 2 3]


[[1 2 3]
 [4 5 6]]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Task 3a: Accessing Array Attributes

In the practice notebook, perform the following.

- Create a NumPy array.
- Write code that prints these attributes (one per line): `ndim`, `shape`, `size`, `dtype`, `itemsize`, `data`, `nbytes`.
- Add a comment line, before each line describing what value the attribute returns. 


In [3]:
NumPy_array=np.array([[2,4,16],[3,9,81]])
#I plagiarized some of these comments from the NumPy reference page 
#number of array dimensions
print(NumPy_array.ndim)
#Dimminsions of the array the above is a 2x3
print(NumPy_array.shape)
#Number of items in array
print(NumPy_array.size)
#What the data type is, for example these are integers 
print(NumPy_array.dtype)
#Length of one array element in bytes.
print(NumPy_array.itemsize)
#Python buffer object pointing to the start of the array’s data.
print(NumPy_array.data)
#Total bytes consumed by the elements of the array.
print(NumPy_array.nbytes)

2
(2, 3)
6
int32
4
24


## Task 4a: Initializing Arrays

In the practice notebook, perform the following.

+ Create an initialized array by using these functions:  `ones`, `zeros`, `empty`, `full`, `arange`, `linspace` and `random.random`. Be sure to follow each array creation with a call to `print()` to display your newly created arrays. 
+ Add a comment above each function call describing what is being done.  

In [4]:
#creates an array of ones, the command below prints a 3D array 
print(np.ones((3,3,2)))
print('\n')
#creates an array of zeros, the command below prints a 1D array 
print(np.zeros((20)))
print('\n')
#creates an empty array, the command below prints a 2D array
print(np.empty((10,2)))
print('\n')
#creates an array full of whatever you provide
#the command below prints a 3D array full of cats
print(np.full((3,4,2),'cats'))
print('\n')
#creates an array full of numbers counted according to the third number you provide
print(np.arange(1,10,3))
print('\n')
#creats an array full of numbers between the two supplies numbers that are evenly spaced
print(np.linspace(0,10))
print('\n')
#Generates a 1D array or single random number(s)
print(np.random.random(10))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


[[['cats' 'cats']
  ['cats' 'cats']
  ['cats' 'cats']
  ['cats' 'cats']]

 [['cats' 'cats']
  ['cats' 'cats']
  ['cats' 'cats']
  ['cats' 'cats']]

 [['cats' 'cats']
  ['cats' 'cats']
  ['cats' 'cats']
  ['cats' 'cats']]]


[1 4 7]


[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694


## Task 5a:  Broadcasting Arrays

In the practice notebook, perform the following.

+ Create two arrays of differing sizes but compatible with broadcasting.
+ Perform addition, multiplication and subtraction.
+ Create two additional arrays of differing size that do not meet the rules for broadcasting and try a mathematical operation.  

In [5]:
array_one=np.random.random((10))
array_two=np.random.random((2,10))
print(array_one-array_two)
print('\n')
print(array_one+array_two)
print('\n')
print(array_one*array_two)
print('\n')
array_three=np.random.random((2))
array_four=np.random.random((3,3))
print('\n')
print(array_three-array_four)

[[ 0.51167466  0.4780744  -0.35522115  0.0491229  -0.32277182 -0.02376004
   0.76686209  0.14030627  0.03884029  0.87905545]
 [ 0.36446156 -0.1934171  -0.06721571  0.0931061  -0.12667822 -0.6313844
   0.72205296 -0.00201174 -0.1931555   0.31640611]]


[[1.28430815 0.84167434 1.29702531 0.14480646 1.46887245 0.29547469
  1.040873   1.18544569 1.02863829 1.07414379]
 [1.43152125 1.51316584 1.00901987 0.10082327 1.27277886 0.90309904
  1.08568213 1.3277637  1.26063407 1.63679313]]


[[3.46909119e-01 1.19965140e-01 3.89023148e-01 4.63896311e-03
  5.13351160e-01 2.16851876e-02 1.23834780e-01 3.46398908e-01
  2.64147040e-01 9.52615961e-02]
 [4.79105216e-01 5.63065170e-01 2.53400786e-01 3.74146661e-04
  4.00979661e-01 1.04235406e-01 1.64336299e-01 4.40738099e-01
  3.87972304e-01 6.44744733e-01]]






ValueError: operands could not be broadcast together with shapes (2,) (3,3) 

## Task 6a: Math/Stats Aggregate Functions

In the practice notebook, perform the following.

+ Create three to five arrays
+ Experiment with each of the aggregation functions: `sum`, `minimum`, `maximum`, `cumsum`, `mean`, `np.corrcoef`, `np.std`, `np.var`. 
+ For each function call, add a comment line above it that describes what it does.  
```


In [6]:
array_one=np.random.random((2,3))
array_two=np.random.random((2,3))
array_three=np.random.random((2,6))
array_four=np.random.random((6,3))
array_five=np.random.random((10,6))
#sums the array's elements
print(np.sum(array_one))
print('\n')
#Creates an array of min values after comparing each element of two arrays
print(np.minimum(array_one,array_two))
print('\n')
#Creates an array of max values after comparing each element of two arrays
print(np.maximum(array_one,array_two))
print('\n')
#Creats an array where each element is equal to all prior elements + that element
print(np.cumsum(array_three))
print('\n')
#calculates the mean of a array
print(np.mean(array_three))
print('\n')
#prints the pearson product-moment correlation coefficent 
print(np.corrcoef(array_four))
print('\n')
#calculates the standard dev
print(np.std(array_five))
print('\n')
#calculates the variance 
print(np.var(array_five))

3.19892089265717


[[0.74614954 0.48733947 0.35815415]
 [0.60208664 0.02614105 0.31638868]]


[[0.81119553 0.64276772 0.97901606]
 [0.61906695 0.09001046 0.91518062]]


[0.76379194 1.46133358 1.94333744 2.84201367 3.21268364 3.24181139
 3.51992281 4.4495211  4.97616311 5.78705625 6.3602281  6.78347129]


0.5652892741856526


[[ 1.          0.7160409   0.67449319 -0.94967769  0.99936035  0.99956832]
 [ 0.7160409   1.         -0.03239853 -0.4613561   0.74054647  0.69522303]
 [ 0.67449319 -0.03239853  1.         -0.87180203  0.64765974  0.69589253]
 [-0.94967769 -0.4613561  -0.87180203  1.         -0.93786872 -0.95847032]
 [ 0.99936035  0.74054647  0.64765974 -0.93786872  1.          0.99787829]
 [ 0.99956832  0.69522303  0.69589253 -0.95847032  0.99787829  1.        ]]


0.26370096727356757


0.06953820014101514


## Task 6b: Logical Aggregate Functions

In the practice notebook, perform the following.

+ Create two arrays containing boolean values.
+ Experiment with each of the aggregation functions: `logical_and`, `logical_or`, `logical_not`. 
+ For each function call, add a comment line above it that describes what it does.  
```

In [7]:
array1=[True, True, True, False, False, True]
array2=[False, False, False, False, True, True]
#checks to see if both elements of 2 arrays are true at a given spot
print(np.logical_and(array1,array2))
#checks to see if 1 of the two elements of 2 arrays are true at a given spot
print(np.logical_or(array1,array2))
#checks to see if an element in an array is false
print(np.logical_not(array1))
print(np.logical_not(array2))

[False False False False False  True]
[ True  True  True False  True  True]
[False False False  True  True False]
[ True  True  True  True False False]
